# Generated by Django 6.0.2 on 2026-05-15 17:20

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookings', '0002_alter_booking_options_alter_booking_apartment_and_more'),
        ('notifications', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='notification',
            name='booking',
            field=models.ForeignKey(
                blank=True,
                help_text='The booking related to this notification, when applicable.',
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name='notifications',
                to='bookings.booking',
                verbose_name='Booking',
            ),
        ),
        migrations.AddField(
            model_name='notification',
            name='event_type',
            field=models.CharField(
                choices=[
                    ('booking_created', 'Booking created'),
                    ('booking_status_changed', 'Booking status changed'),
                    ('booking_cancelled', 'Booking cancelled'),
                ],
                default='booking_created',
                help_text='Machine-readable notification event type.',
                max_length=50,
                verbose_name='Event type',
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='notification',
            name='metadata',
            field=models.JSONField(
                blank=True,
                default=dict,
                help_text='Structured event payload for clients.',
                verbose_name='Metadata',
            ),
        ),
        migrations.AlterModelOptions(
            name='notification',
            options={
                'ordering': ['-id'],
                'verbose_name': 'Notification',
                'verbose_name_plural': 'Notifications',
            },
        ),
        migrations.AddIndex(
            model_name='notification',
            index=models.Index(fields=['user', 'id'], name='notificatio_user_id_2fb0ab_idx'),
        ),
    ]
