# Generated by Django 6.0.2 on 2026-05-16 08:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notifications', '0002_notification_event_type_notification_booking_and_more'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='notification',
            new_name='notificatio_user_id_93f365_idx',
            old_name='notificatio_user_id_2fb0ab_idx',
        ),
        migrations.AddField(
            model_name='notification',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, help_text='The date and time when the record was last updated.', verbose_name='Updated at'),
        ),
        migrations.AlterField(
            model_name='notification',
            name='message',
            field=models.TextField(help_text='Human-readable notification message.', verbose_name='Message'),
        ),
    ]
