# Generated by Django 6.0.2 on 2026-05-15 07:36

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookings', '0001_initial'),
        ('properties', '0004_alter_apartment_options_alter_city_options_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='booking',
            options={'ordering': ['-created_at'], 'verbose_name': 'booking', 'verbose_name_plural': 'bookings'},
        ),
        migrations.AlterField(
            model_name='booking',
            name='apartment',
            field=models.ForeignKey(help_text='The apartment being booked.', on_delete=django.db.models.deletion.CASCADE, related_name='bookings', to='properties.apartment', verbose_name='apartment'),
        ),
        migrations.AlterField(
            model_name='booking',
            name='check_in',
            field=models.DateField(db_index=True, help_text='The date the tenant plan to move in.', verbose_name='check-in date'),
        ),
        migrations.AlterField(
            model_name='booking',
            name='check_out',
            field=models.DateField(db_index=True, help_text='The date the tenant plan to move out.', verbose_name='check-out date'),
        ),
        migrations.AlterField(
            model_name='booking',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, db_index=True, help_text='The date and time when this booking record was created.', verbose_name='created at'),
        ),
        migrations.AlterField(
            model_name='booking',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('confirmed', 'Confirmed'), ('completed', 'Completed'), ('cancelled', 'Cancelled')], db_index=True, default='pending', help_text='The current lifecycle stage of the booking.', max_length=20, verbose_name='status'),
        ),
        migrations.AlterField(
            model_name='booking',
            name='tenant',
            field=models.ForeignKey(help_text='The user who is making the booking.', on_delete=django.db.models.deletion.CASCADE, related_name='bookings', to=settings.AUTH_USER_MODEL, verbose_name='tenant'),
        ),
        migrations.AlterField(
            model_name='booking',
            name='total_price',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='The total cost of the stay, auto-calculated based on nights.', max_digits=10, validators=[django.core.validators.MinValueValidator(0)], verbose_name='total price'),
        ),
        migrations.AddIndex(
            model_name='booking',
            index=models.Index(fields=['check_in', 'check_out'], name='bookings_bo_check_i_3b9851_idx'),
        ),
        migrations.AddIndex(
            model_name='booking',
            index=models.Index(fields=['tenant', 'status'], name='bookings_bo_tenant__58bfba_idx'),
        ),
        migrations.AddConstraint(
            model_name='booking',
            constraint=models.CheckConstraint(condition=models.Q(('check_out__gt', models.F('check_in'))), name='booking_checkout_after_checkin', violation_error_message='check_out must be after check_in'),
        ),
    ]
