# Generated by Django 6.0.2 on 2026-05-16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_remove_customuser_avatar'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='avatar',
            field=models.ImageField(
                blank=True,
                help_text='Optional profile photo for the user.',
                null=True,
                upload_to='avatars/',
                verbose_name='Avatar',
            ),
        ),
    ]
