# Generated by Django 6.0.2 on 2026-05-16 08:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
        ('users', '0004_customuser_role_constraint'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='customuser',
            options={'verbose_name': 'User', 'verbose_name_plural': 'Users'},
        ),
        migrations.AlterField(
            model_name='customuser',
            name='email',
            field=models.EmailField(help_text='Unique identifier for the user.', max_length=254, unique=True, verbose_name='Email address'),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='first_name',
            field=models.CharField(help_text="User's given name.", max_length=255, verbose_name='First name'),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='is_active',
            field=models.BooleanField(default=True, help_text='Designates whether this user should be treated as active.', verbose_name='Is active'),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='is_landlord',
            field=models.BooleanField(default=False, help_text='Designates whether the user can list apartments.', verbose_name='Is landlord'),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='is_renter',
            field=models.BooleanField(default=False, help_text='Designates whether the user can book apartments.', verbose_name='Is renter'),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='is_staff',
            field=models.BooleanField(default=False, help_text='Designates whether the user can log into this admin site.', verbose_name='Is staff'),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='last_name',
            field=models.CharField(help_text="User's family name.", max_length=255, verbose_name='Last name'),
        ),
        migrations.AddIndex(
            model_name='customuser',
            index=models.Index(fields=['email'], name='users_custo_email_c80f75_idx'),
        ),
        migrations.AddIndex(
            model_name='customuser',
            index=models.Index(fields=['is_landlord'], name='users_custo_is_land_0af279_idx'),
        ),
        migrations.AddIndex(
            model_name='customuser',
            index=models.Index(fields=['is_renter'], name='users_custo_is_rent_8e9921_idx'),
        ),
    ]
