# Generated by Django 6.0.2 on 2026-05-11 12:06

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('properties', '0003_alter_city_options_alter_country_options'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='apartment',
            options={'ordering': ['-created_at'], 'verbose_name': 'apartment', 'verbose_name_plural': 'apartments'},
        ),
        migrations.AlterModelOptions(
            name='city',
            options={'ordering': ['name'], 'verbose_name': 'city', 'verbose_name_plural': 'cities'},
        ),
        migrations.AlterModelOptions(
            name='country',
            options={'ordering': ['name'], 'verbose_name': 'country', 'verbose_name_plural': 'countries'},
        ),
        migrations.AlterField(
            model_name='apartment',
            name='address',
            field=models.CharField(help_text='The physical address of the apartment.', max_length=255, verbose_name='address'),
        ),
        migrations.AlterField(
            model_name='apartment',
            name='city',
            field=models.ForeignKey(help_text='The city where the apartment is located.', on_delete=django.db.models.deletion.CASCADE, related_name='apartments', to='properties.city', verbose_name='city'),
        ),
        migrations.AlterField(
            model_name='apartment',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, db_index=True, help_text='The date and time when the listing was created.', verbose_name='created at'),
        ),
        migrations.AlterField(
            model_name='apartment',
            name='description',
            field=models.TextField(help_text='A detailed description of the apartment.', verbose_name='description'),
        ),
        migrations.AlterField(
            model_name='apartment',
            name='owner',
            field=models.ForeignKey(help_text='The user who owns this apartment listing.', on_delete=django.db.models.deletion.CASCADE, related_name='apartments', to=settings.AUTH_USER_MODEL, verbose_name='owner'),
        ),
        migrations.AlterField(
            model_name='apartment',
            name='price_per_night',
            field=models.DecimalField(db_index=True, decimal_places=2, help_text='The cost to rent the apartment for one night.', max_digits=10, validators=[django.core.validators.MinValueValidator(0)], verbose_name='price per night'),
        ),
        migrations.AlterField(
            model_name='apartment',
            name='rooms',
            field=models.PositiveIntegerField(db_index=True, help_text='The number of rooms available in the apartment.', validators=[django.core.validators.MinValueValidator(1)], verbose_name='rooms'),
        ),
        migrations.AlterField(
            model_name='apartment',
            name='title',
            field=models.CharField(help_text='The title of the apartment listing.', max_length=255, verbose_name='title'),
        ),
        migrations.AlterField(
            model_name='city',
            name='country',
            field=models.ForeignKey(blank=True, help_text='The country this city belongs to.', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='cities', to='properties.country', verbose_name='country'),
        ),
        migrations.AlterField(
            model_name='city',
            name='name',
            field=models.CharField(help_text='The name of the city.', max_length=100, verbose_name='name'),
        ),
        migrations.AlterField(
            model_name='country',
            name='name',
            field=models.CharField(help_text='The unique name of the country.', max_length=100, unique=True, verbose_name='name'),
        ),
    ]
