# Generated by Django 6.0.2 on 2026-05-16 08:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('properties', '0004_alter_apartment_options_alter_city_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='apartment',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, help_text='The date and time when the record was last updated.', verbose_name='Updated at'),
        ),
        migrations.AlterField(
            model_name='apartment',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, db_index=True, help_text='The date and time when the record was created.', verbose_name='Created at'),
        ),
    ]
